name: Deploy Cloud Function
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: distrava-318517
          export_default_credentials: true
      - run: npm install
      - run: npm run compile
      - id: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: distrava
          region: us-central1
          runtime: nodejs14
          env_vars: DISCORD_APPLICATION_ID=${{ secrets.DISCORD_APPLICATION_ID }},DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }},DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }},MAPBOX_STATIC_MAPS_ACCESS_TOKEN=${{ secrets.MAPBOX_STATIC_MAPS_ACCESS_TOKEN }},STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }},STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }},STRAVA_REDIRECT_URI=${{ secrets.STRAVA_REDIRECT_URI }},GOOGLE_PUBSUB_INTERACTION_TOPIC=${{ secrets.GOOGLE_PUBSUB_INTERACTION_TOPIC }},GOOGLE_PUBSUB_STRAVA_WEBHOOK_TOPIC=${{ secrets.GOOGLE_PUBSUB_STRAVA_WEBHOOK_TOPIC }},ENVIRONMENT=${{ secrets.ENVIRONMENT }},SIGNING_SECRET=${{ secrets.SIGNING_SECRET }}
