name: Deploy Cloud Function
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: distrava-318517
          export_default_credentials: true
      - run: npm run compile
      - id: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: distrava
          region: us-central1
          runtime: nodejs14
          env_vars: DISCORD_APPLICATION_ID=${{ secrets.DISCORD_APPLICATION_ID }},DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }},DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }},GOOGLE_MAPS_STATIC_API_KEY=${{ secrets.GOOGLE_MAPS_STATIC_API_KEY }},STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }},STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}
